# Build AdonisJS
FROM node:16-alpine
# Set directory for all files
WORKDIR /app
# Copy over package.json files
COPY package*.json ./
# Install all packages
# RUN npm install
# Copy over source code
COPY . .

# Start server up
CMD npm install && npm run watch
