version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: prod.Dockerfile
    network_mode: host # for not mac
    env_file:
      - .env.production
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    network_mode: host # for not mac
    ports:
      - "6379:6379"
    expose:
      - "6379"

