// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Events  string
	Groups  string
	Olders  string
	Sources string
	Users   string
}{
	Events:  "events",
	Groups:  "groups",
	Olders:  "olders",
	Sources: "sources",
	Users:   "users",
}
