// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Events         string
	GorpMigrations string
	Groups         string
	Olders         string
	Sources        string
	UserIdstrings  string
	UserOlders     string
	Users          string
}{
	Events:         "events",
	GorpMigrations: "gorp_migrations",
	Groups:         "groups",
	Olders:         "olders",
	Sources:        "sources",
	UserIdstrings:  "user_idstrings",
	UserOlders:     "user_olders",
	Users:          "users",
}
