// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Events", testEventsUpsert)

	t.Run("GorpMigrations", testGorpMigrationsUpsert)

	t.Run("Groups", testGroupsUpsert)

	t.Run("Olders", testOldersUpsert)

	t.Run("Sources", testSourcesUpsert)

	t.Run("UserIdstrings", testUserIdstringsUpsert)

	t.Run("UserOlders", testUserOldersUpsert)

	t.Run("Users", testUsersUpsert)
}
