// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserOlders(t *testing.T) {
	t.Parallel()

	query := UserOlders()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserOldersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserOldersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserOlders().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserOldersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserOlderSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserOldersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserOlderExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserOlder exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserOlderExists to return true, but got false.")
	}
}

func testUserOldersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userOlderFound, err := FindUserOlder(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userOlderFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserOldersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserOlders().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserOldersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserOlders().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserOldersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userOlderOne := &UserOlder{}
	userOlderTwo := &UserOlder{}
	if err = randomize.Struct(seed, userOlderOne, userOlderDBTypes, false, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}
	if err = randomize.Struct(seed, userOlderTwo, userOlderDBTypes, false, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = userOlderOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userOlderTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserOlders().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserOldersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userOlderOne := &UserOlder{}
	userOlderTwo := &UserOlder{}
	if err = randomize.Struct(seed, userOlderOne, userOlderDBTypes, false, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}
	if err = randomize.Struct(seed, userOlderTwo, userOlderDBTypes, false, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = userOlderOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userOlderTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userOlderBeforeInsertHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func userOlderAfterInsertHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func userOlderAfterSelectHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func userOlderBeforeUpdateHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func userOlderAfterUpdateHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func userOlderBeforeDeleteHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func userOlderAfterDeleteHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func userOlderBeforeUpsertHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func userOlderAfterUpsertHook(e boil.Executor, o *UserOlder) error {
	*o = UserOlder{}
	return nil
}

func testUserOldersHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &UserOlder{}
	o := &UserOlder{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userOlderDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserOlder object: %s", err)
	}

	AddUserOlderHook(boil.BeforeInsertHook, userOlderBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userOlderBeforeInsertHooks = []UserOlderHook{}

	AddUserOlderHook(boil.AfterInsertHook, userOlderAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userOlderAfterInsertHooks = []UserOlderHook{}

	AddUserOlderHook(boil.AfterSelectHook, userOlderAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userOlderAfterSelectHooks = []UserOlderHook{}

	AddUserOlderHook(boil.BeforeUpdateHook, userOlderBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userOlderBeforeUpdateHooks = []UserOlderHook{}

	AddUserOlderHook(boil.AfterUpdateHook, userOlderAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userOlderAfterUpdateHooks = []UserOlderHook{}

	AddUserOlderHook(boil.BeforeDeleteHook, userOlderBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userOlderBeforeDeleteHooks = []UserOlderHook{}

	AddUserOlderHook(boil.AfterDeleteHook, userOlderAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userOlderAfterDeleteHooks = []UserOlderHook{}

	AddUserOlderHook(boil.BeforeUpsertHook, userOlderBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userOlderBeforeUpsertHooks = []UserOlderHook{}

	AddUserOlderHook(boil.AfterUpsertHook, userOlderAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userOlderAfterUpsertHooks = []UserOlderHook{}
}

func testUserOldersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserOldersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(userOlderColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserOlderToOneOlderUsingOlder(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local UserOlder
	var foreign Older

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, olderDBTypes, false, olderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Older struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.OlderID, foreign.ID)
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Older().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserOlderSlice{&local}
	if err = local.L.LoadOlder(tx, false, (*[]*UserOlder)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Older == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Older = nil
	if err = local.L.LoadOlder(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Older == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserOlderToOneUserUsingUser(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local UserOlder
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.UserID, foreign.ID)
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserOlderSlice{&local}
	if err = local.L.LoadUser(tx, false, (*[]*UserOlder)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserOlderToOneSetOpOlderUsingOlder(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a UserOlder
	var b, c Older

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userOlderDBTypes, false, strmangle.SetComplement(userOlderPrimaryKeyColumns, userOlderColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, olderDBTypes, false, strmangle.SetComplement(olderPrimaryKeyColumns, olderColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, olderDBTypes, false, strmangle.SetComplement(olderPrimaryKeyColumns, olderColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Older{&b, &c} {
		err = a.SetOlder(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Older != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserOlders[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.OlderID, x.ID) {
			t.Error("foreign key was wrong value", a.OlderID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.OlderID))
		reflect.Indirect(reflect.ValueOf(&a.OlderID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.OlderID, x.ID) {
			t.Error("foreign key was wrong value", a.OlderID, x.ID)
		}
	}
}

func testUserOlderToOneRemoveOpOlderUsingOlder(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a UserOlder
	var b Older

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userOlderDBTypes, false, strmangle.SetComplement(userOlderPrimaryKeyColumns, userOlderColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, olderDBTypes, false, strmangle.SetComplement(olderPrimaryKeyColumns, olderColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetOlder(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveOlder(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Older().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Older != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.OlderID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.UserOlders) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testUserOlderToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a UserOlder
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userOlderDBTypes, false, strmangle.SetComplement(userOlderPrimaryKeyColumns, userOlderColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserOlders[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testUserOlderToOneRemoveOpUserUsingUser(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a UserOlder
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userOlderDBTypes, false, strmangle.SetComplement(userOlderPrimaryKeyColumns, userOlderColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUser(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUser(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.User().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.User != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.UserID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.UserOlders) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testUserOldersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testUserOldersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserOlderSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testUserOldersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserOlders().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userOlderDBTypes = map[string]string{`ID`: `integer`, `UserID`: `integer`, `OlderID`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                = bytes.MinRead
)

func testUserOldersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userOlderPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userOlderAllColumns) == len(userOlderPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserOldersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userOlderAllColumns) == len(userOlderPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserOlder{}
	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userOlderDBTypes, true, userOlderPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userOlderAllColumns, userOlderPrimaryKeyColumns) {
		fields = userOlderAllColumns
	} else {
		fields = strmangle.SetComplement(
			userOlderAllColumns,
			userOlderPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserOlderSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserOldersUpsert(t *testing.T) {
	t.Parallel()

	if len(userOlderAllColumns) == len(userOlderPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserOlder{}
	if err = randomize.Struct(seed, &o, userOlderDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserOlder: %s", err)
	}

	count, err := UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userOlderDBTypes, false, userOlderPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserOlder struct: %s", err)
	}

	if err = o.Upsert(tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserOlder: %s", err)
	}

	count, err = UserOlders().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
